#!/usr/bin/env bash
#Install ngnix on your web-01 server

apt-get -y update
apt-get -y install nginx
ufw allow "Nginx HTTP"
echo "Holberton School" > /var/www/html/index.nginx-debian.html
service ngnix start