#!/usr/bin/env bash
#Install ngnix on your web-01 server

sudo apt-get -y update
sudo apt-get -y install nginx
sudo echo 'Holberton School' | sudo tee /var/www/html/index.html
sudo sed -i "/server_name _;/ i rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
sudo sed -i "/server_name _;/ i error_page 404 /404.html;" /etc/nginx/sites-available/default
sudo sed -i "/listen 80 default_server;/ i add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
sudo service nginx start

